### ISSUE TITLE
v0.49 release for JDK 22 compatibility?

### ISSUE THREAD

**Issue by mmoayyed** [rzwitserloot/lombok.patcher#14]
The patcher was updated [here](https://github.com/projectlombok/lombok.patcher/commit/f06f505440c6c84bddd149517eebd272c7655f9d) to support JDK 22. Could you please publish a new v0.49  release that allows it to be used in Project Lombok?

**Comment by rzwitserloot** [comment]
v0.50 has been published. (even numbers are intended to be stable releases, odd numbers are `-SNAPSHOT` style releases).
