### ISSUE TITLE
Support JDK23

### ISSUE THREAD

**Issue by Eng-Fouad** [rzwitserloot/lombok.patcher#16]
The patcher was updated [here](https://github.com/projectlombok/lombok.patcher/commit/b4475fe76814e3bfaa9487af129bf0b363416cd9) to support JDK 23. Could you please publish a new v0.52 release that allows it to be used in Project Lombok?

cc @rzwitserloot @mmoayyed 

https://github.com/projectlombok/lombok/issues/3722

**Comment by rzwitserloot** [comment]
The v0.52 release is out and includes the update.
