### ISSUE TITLE
Build error due to stale JUnit 4.8.1 dependency

### ISSUE THREAD

**Issue by kgeorgiy** [rzwitserloot/lombok.patcher#3]
JUnit 4.8.1 dependency specifies https://cloud.github.com/downloads/KentBeck/junit/junit-4.8.1.jar as an artifact location. This link is no longer available neither at https://cloud.github.com nor https://cloud.githubusercontent.com.

Proposed fix: [update JUnit version to 4.12 and use the standard repository](/rzwitserloot/lombok.patcher/pull/4).

**Comment by rzwitserloot** [comment]
Thanks for the PR :) applied.
