### ISSUE TITLE
Java 17 (EA) compatibility

### ISSUE THREAD

**Issue by ginkel** [rzwitserloot/lombok.patcher#8]
`lombok.patcher` currently uses ASM 9.0, which does not include Java 17 support. Upgrading to ASM 9.1 would resolve this as v9.1 includes support for Java 17 class files.

**Comment by rspilker** [comment]
Fixed in 98a3cac74da7d3131f34c52df591fd4a651241b4

**Comment by ginkel** [comment]
Excellent, thanks! :-) Would be great if the update could make it into the next Lombok release.

**Comment by rspilker** [comment]
It will.
